//! Agent-layer parity surfaces from `agent/`.

pub mod auxiliary_client;
pub mod billing_links;
pub mod bounded_response;
pub mod config;
pub mod credential_pool;
pub mod credential_store;
pub mod errors;
pub mod interrupt_compat;
pub mod iteration_budget;
pub mod kanban_stop;
pub mod lmstudio_reasoning;
pub mod managed_scope;
pub mod manual_compression_feedback;
pub mod message_content;
pub mod monitoring;
pub mod portal_tags;
pub mod markdown_tables;
pub mod reactions;
pub mod reasoning_summaries;
pub mod secret_sources;
pub mod ssl_guard;
pub mod think_scrubber;
pub mod tool_result_classification;
pub mod trajectory;
pub mod verify;
pub mod turn_retry_state;
pub mod verify_hooks;
