//! AES-256-GCM utilities for QQBot scan-to-configure credential decryption.
//!
//! PARITY: `gateway/platforms/qqbot/crypto.py` @ b9aa928 (whole module).
//!
//! Ciphertext layout (after base64-decoding):
//!
//! ```text
//! IV (12 bytes) ‖ ciphertext (N bytes) ‖ AuthTag (16 bytes)
//! ```
//!
//! This matches the `cryptography` library's AESGCM attachment scheme
//! (tag appended to the ciphertext), which is what the QQBot portal server
//! produces.

use base64::engine::general_purpose::STANDARD as BASE64;
use base64::Engine;

/// Generate a 256-bit random AES key and return it as base64.
///
/// The key is passed to `create_bind_task` so the server can encrypt the
/// bot's *client_secret* before returning it. Only this CLI holds the key,
/// ensuring the secret never travels in plaintext.
///
/// PARITY: `generate_bind_key` (upstream lines 12-18).
pub fn generate_bind_key() -> String {
    BASE64.encode(rand::random::<[u8; 32]>())
}

/// Decrypt a base64-encoded AES-256-GCM ciphertext.
///
/// * `encrypted_base64` — the `bot_encrypt_secret` value from
///   `poll_bind_result`.
/// * `key_base64` — the base64 AES key generated by [`generate_bind_key`].
///
/// Returns the decrypted *client_secret* as a UTF-8 string. Errors
/// (bad base64, wrong key, tampered ciphertext, non-UTF-8 plaintext)
/// propagate as `Err` — upstream lets the exception raise.
///
/// PARITY: `decrypt_secret` (upstream lines 20-44).
pub fn decrypt_secret(encrypted_base64: &str, key_base64: &str) -> Result<String, String> {
    use aes_gcm::aead::Aead;
    use aes_gcm::{Aes256Gcm, KeyInit};

    let key = BASE64
        .decode(key_base64)
        .map_err(|e| format!("invalid key base64: {e}"))?;
    let raw = BASE64
        .decode(encrypted_base64)
        .map_err(|e| format!("invalid encrypted base64: {e}"))?;
    if raw.len() < 12 + 16 {
        return Err("ciphertext too short for IV + tag".to_string());
    }

    let iv = &raw[..12];
    // AESGCM expects ciphertext + tag concatenated — the aes-gcm crate does
    // too.
    let ciphertext_with_tag = &raw[12..];

    let cipher = Aes256Gcm::new_from_slice(&key).map_err(|e| format!("bad key length: {e}"))?;
    let nonce = aes_gcm::Nonce::from_slice(iv);
    let plaintext = cipher
        .decrypt(nonce, ciphertext_with_tag)
        .map_err(|_| "decryption failed (wrong key or tampered ciphertext)".to_string())?;
    String::from_utf8(plaintext).map_err(|_| "decrypted secret is not UTF-8".to_string())
}
