#!/usr/bin/env python3
"""Regenerate crates/hermes-toolsets/src/data.rs from the pinned upstream clone.

AST-parses upstream toolsets.py + toolset_distributions.py (handling list
concatenations like _HERMES_CORE_TOOLS + [...] and scalar `posture` keys)
and emits the Rust static table 1:1.
"""
import ast
import json
import os
import sys

UPSTREAM = os.environ.get("HERMES_UPSTREAM", "/home/mustbearn/Projects/Research/hermes-agent-repo")
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "crates", "hermes-toolsets", "src", "data.rs"))


def val(node, mod):
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.Name):
        if node.id in mod:
            return val(mod[node.id], mod)
        return None
    if isinstance(node, (ast.List, ast.Tuple)):
        return [x.value for x in node.elts if isinstance(x, ast.Constant)]
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        l, r = val(node.left, mod), val(node.right, mod)
        if isinstance(l, list) and isinstance(r, list):
            return l + r
        return None
    if isinstance(node, ast.Dict):
        out = {}
        for k, vv in zip(node.keys, node.values):
            if isinstance(k, ast.Constant):
                v = val(vv, mod)
                if v is not None:
                    out[k.value] = v
        return out
    return None


def parse(path):
    tree = ast.parse(open(path).read())
    mod = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name):
                    mod[t.id] = node.value
    return mod


def rust_str_list(items):
    if items is None:
        items = []
    return "&[\n" + "".join('        "{}",\n'.format(s) for s in items) + "    ]"


def main():
    ts_mod = parse(os.path.join(UPSTREAM, "toolsets.py"))
    core = val(ts_mod.get("_HERMES_CORE_TOOLS"), ts_mod)
    webhook = val(ts_mod.get("_HERMES_WEBHOOK_SAFE_TOOLS"), ts_mod)
    toolsets = val(ts_mod.get("TOOLSETS"), ts_mod) or {}

    dist_mod = parse(os.path.join(UPSTREAM, "toolset_distributions.py"))
    distributions = val(dist_mod.get("DISTRIBUTIONS"), dist_mod) or {}

    out = []
    out.append("//! Static toolset / distribution data, generated 1:1 from upstream\n")
    out.append("//! toolsets.py TOOLSETS / _HERMES_CORE_TOOLS / _HERMES_WEBHOOK_SAFE_TOOLS and\n")
    out.append("//! toolset_distributions.py DISTRIBUTIONS @ b9aa928.\n")
    out.append("//! GENERATED by tools/gen_toolsets.py \u2014 do not edit by hand.\n")
    out.append("\n#[derive(Debug, Clone)]\npub struct ToolsetDef {\n    pub description: &'static str,\n    pub tools: &'static [&'static str],\n    pub includes: &'static [&'static str],\n    pub posture: bool,\n}\n")
    out.append("pub const HERMES_CORE_TOOLS: &[&str] = " + rust_str_list(core) + ";\n")
    out.append("pub const HERMES_WEBHOOK_SAFE_TOOLS: &[&str] = " + rust_str_list(webhook) + ";\n")
    out.append("\npub static TOOLSETS: &[(&str, ToolsetDef)] = &[\n")
    for name, ts in toolsets.items():
        desc = str(ts.get("description", "")).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        tools = rust_str_list(ts.get("tools"))
        incl = rust_str_list(ts.get("includes"))
        posture = "true" if ts.get("posture") else "false"
        out.append('    ("{}", ToolsetDef {{\n        description: "{}",\n        tools: {},\n        includes: {},\n        posture: {},\n    }}),\n'.format(name, desc, tools, incl, posture))
    out.append("];\n")

    out.append("\n#[derive(Debug, Clone)]\npub struct DistributionDef {\n    pub description: &'static str,\n    pub toolsets: &'static [(&'static str, u32)],\n}\n")
    out.append("pub static DISTRIBUTIONS: &[(&str, DistributionDef)] = &[\n")
    for name, dist in distributions.items():
        desc = str(dist.get("description", "")).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        out.append('    ("{}", DistributionDef {{\n        description: "{}",\n        toolsets: &[\n'.format(name, desc))
        for tn, p in (dist.get("toolsets") or {}).items():
            out.append('            ("{}", {}),\n'.format(tn, p))
        out.append('        ],\n    }),\n')
    out.append("];\n")

    with open(OUT, "w") as f:
        f.write("".join(out))
    print("wrote", OUT, "(" + str(len(out)) + " lines)")


if __name__ == "__main__":
    sys.exit(main())
