#!/usr/bin/env python3
"""Regenerate crates/hermes-toolsets/src/data.rs from the pinned upstream clone.

Executes the pinned toolsets.py + toolset_distributions.py (TOOLSETS is now
computed via _ts()/_bundle()/_core_without() — a plain AST walk can no longer
evaluate it) and emits the Rust static table 1:1.
"""
import json
import os
import subprocess
import sys

UPSTREAM = os.environ.get("HERMES_UPSTREAM", "/home/mustbearn/Projects/Research/hermes-agent-repo")
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "crates", "hermes-toolsets", "src", "data.rs"))

EXTRACT = r'''
import json, sys
sys.path.insert(0, %r)
import toolsets, toolset_distributions
core = toolsets._HERMES_CORE_TOOLS
webhook = toolsets._HERMES_WEBHOOK_SAFE_TOOLS
toolsets_dict = toolsets.TOOLSETS
dists = toolset_distributions.DISTRIBUTIONS
# Serialize: keep key order (Python dict preserves insertion order).
print(json.dumps({
    "core": core,
    "webhook": webhook,
    "toolsets": toolsets_dict,
    "distributions": dists,
}, ensure_ascii=False))
''' % UPSTREAM


def rust_str_list(items):
    if items is None:
        items = []
    return "&[\n" + "".join('        "{}",\n'.format(s) for s in items) + "    ]"


def esc(s):
    return str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    result = subprocess.run(
        [sys.executable, "-c", EXTRACT],
        capture_output=True, text=True, check=True,
    )
    data = json.loads(result.stdout)

    out = []
    out.append("//! Static toolset / distribution data, generated 1:1 from upstream\n")
    out.append("//! toolsets.py TOOLSETS / _HERMES_CORE_TOOLS / _HERMES_WEBHOOK_SAFE_TOOLS and\n")
    out.append("//! toolset_distributions.py DISTRIBUTIONS @ 5d59366.\n")
    out.append("//! GENERATED by tools/gen_toolsets.py \u2014 do not edit by hand.\n")
    out.append("\n#[derive(Debug, Clone)]\npub struct ToolsetDef {\n    pub description: &'static str,\n    pub tools: &'static [&'static str],\n    pub includes: &'static [&'static str],\n    pub posture: bool,\n    pub module: Option<&'static str>,\n}\n")
    out.append("pub const HERMES_CORE_TOOLS: &[&str] = " + rust_str_list(data["core"]) + ";\n")
    out.append("pub const HERMES_WEBHOOK_SAFE_TOOLS: &[&str] = " + rust_str_list(data["webhook"]) + ";\n")
    out.append("\npub static TOOLSETS: &[(&str, ToolsetDef)] = &[\n")
    for name, ts in data["toolsets"].items():
        desc = esc(ts.get("description", ""))
        tools = rust_str_list(ts.get("tools"))
        incl = rust_str_list(ts.get("includes"))
        posture = "true" if ts.get("posture") else "false"
        module = ('Some("%s")' % esc(ts["module"])) if ts.get("module") else "None"
        out.append('    ("{}", ToolsetDef {{\n        description: "{}",\n        tools: {},\n        includes: {},\n        posture: {},\n        module: {},\n    }}),\n'.format(name, desc, tools, incl, posture, module))
    out.append("];\n")

    out.append("\n#[derive(Debug, Clone)]\npub struct DistributionDef {\n    pub description: &'static str,\n    pub toolsets: &'static [(&'static str, u32)],\n}\n")
    out.append("pub static DISTRIBUTIONS: &[(&str, DistributionDef)] = &[\n")
    for name, dist in data["distributions"].items():
        desc = esc(dist.get("description", ""))
        out.append('    ("{}", DistributionDef {{\n        description: "{}",\n        toolsets: &[\n'.format(name, desc))
        for tn, p in (dist.get("toolsets") or {}).items():
            out.append('            ("{}", {}),\n'.format(tn, p))
        out.append('        ],\n    }),\n')
    out.append("];\n")

    with open(OUT, "w") as f:
        f.write("".join(out))
    print("wrote", OUT, "(" + str(len(out)) + " lines)")


if __name__ == "__main__":
    sys.exit(main())
