import json

d = json.load(open('/tmp/toolsets_data.json'))

def rust_str_list(items):
    if items is None:
        items = []
    return "&[\n" + "".join('        "{}",\n'.format(s) for s in items) + "    ]"

out = []
out.append("//! Static toolset / distribution data, generated 1:1 from upstream\n")
out.append("//! toolsets.py TOOLSETS / _HERMES_CORE_TOOLS / _HERMES_WEBHOOK_SAFE_TOOLS and\n")
out.append("//! toolset_distributions.py DISTRIBUTIONS @ b9aa928.\n")
out.append("//! GENERATED by tools/gen_toolsets.py \u2014 do not edit by hand.\n")
out.append("\n#[derive(Debug, Clone)]\npub struct ToolsetDef {\n    pub description: &'static str,\n    pub tools: &'static [&'static str],\n    pub includes: &'static [&'static str],\n}\n")
out.append("pub const HERMES_CORE_TOOLS: &[&str] = " + rust_str_list(d['core']) + ";\n")
out.append("pub const HERMES_WEBHOOK_SAFE_TOOLS: &[&str] = " + rust_str_list(d['webhook_safe']) + ";\n")
out.append("\npub static TOOLSETS: &[(&str, ToolsetDef)] = &[\n")
for name, ts in d['toolsets'].items():
    desc = ts['description'].replace('\\', '\\\\').replace('"', '\\"').replace("\n", "\\n")
    tools = rust_str_list(ts['tools'])
    incl = rust_str_list(ts['includes'])
    out.append('    ("{}", ToolsetDef {{\n        description: "{}",\n        tools: {},\n        includes: {},\n    }}),\n'.format(name, desc, tools, incl))
out.append("];\n")

out.append("\n#[derive(Debug, Clone)]\npub struct DistributionDef {\n    pub description: &'static str,\n    pub toolsets: &'static [(&'static str, u32)],\n}\n")
out.append("pub static DISTRIBUTIONS: &[(&str, DistributionDef)] = &[\n")
for name, dist in d['distributions'].items():
    desc = dist['description'].replace('\\', '\\\\').replace('"', '\\"').replace("\n", "\\n")
    out.append('    ("{}", DistributionDef {{\n        description: "{}",\n        toolsets: &[\n'.format(name, desc))
    for tn, p in dist['toolsets'].items():
        out.append('            ("{}", {}),\n'.format(tn, p))
    out.append('        ],\n    }),\n')
out.append("];\n")

open('crates/hermes-toolsets/src/data.rs', 'w').write("".join(out))
print("data.rs written:", len(out), "lines")
